### ISSUE TITLE
Metric-based unit tests

### ISSUE THREAD

**Issue by DanielYakubov** [CUNY-CL/udtube#64]
# Current
Currently, our unit tests for the main model training code ultimately rely on diffs between the files. 

# Objective
On top of (not replacing) the diff tests, we should also add tests to check metrics functionality

**Comment by kylebgorman** [comment]
I thought a half-minute about how you'd do this and I think you'd just run `udtube test` on some data, and do a file-based diff. So it's actually not a very big project.
